kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: golang
    commands:
      - make install

  - name: ls-lint
    image: byrnedo/alpine-curl
    commands:
      - curl -sL -o ls-lint https://github.com/loeffel-io/ls-lint/releases/download/v1.10.0/ls-lint-linux && chmod +x ls-lint && ./ls-lint

  - name: linter
    image: golangci/golangci-lint
    commands:
      - make linter

  - name: test
    image: golang
    commands:
      - make test-coverage