kind: pipeline
type: docker
name: docker

steps:
  - name: install
    image: golang
    commands:
      - make install

  - name: ls-lint
    image: byrnedo/alpine-curl
    commands:
      - curl -sL -o ls-lint https://github.com/loeffel-io/ls-lint/releases/download/v1.9.2/ls-lint-linux && chmod +x ls-lint && ./ls-lint

  - name: linter
    image: golangci/golangci-lint
    commands:
      - make linter

  - name: test
    image: golang
    commands:
      - make test-coverage

  - name: codeql
    image: mcr.microsoft.com/cstsectools/codeql-container
    commands:
      - apt-get install golang -y
      - mkdir -p /opt/results
      - codeql database create --language=go /opt/results/source_db -s .
      - codeql database upgrade /opt/results/source_db
      - codeql database analyze /opt/results/source_db --format=sarif-latest --output=/opt/results/issues.sarif go-security-and-quality.qls
    when:
      branch: master
      event: push